package oop.inheritance;

public class Teacher extends Person{
	private String subject;
	
	public Teacher() {
		
	}
	//this'll be generated by select combobox when auto-generate
	public Teacher(String name, int age, String subject) {
		super(name, age);
		this.subject = subject;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public void display() {
		super.display();
		System.out.println("\t과\t목: "+subject);
	}
}
